### ISSUE TITLE
Add DNS records to Terraform.

### ISSUE THREAD

**Issue by DFurnes** [DoSomething/infrastructure#11]
We should add our DNS records to Terraform so we can manage subdomains & hook them up to the right backend in code. I could've sworn DNSMadeEasy was a third-party provider last time I looked, but it turns out it's [included out-of-the-box](https://www.terraform.io/docs/providers/dme/index.html).

**Comment by DFurnes** [comment]
Or not! The Terraform DNSMadeEasy provider [has been archived](https://github.com/terraform-providers/terraform-provider-dme).

**Comment by mshmsh5000** [comment]
Oh snaps! This is an example of why I want a network of Terraform practitioners to lean on.

**Comment by DFurnes** [comment]
Closing in favor of [#165477075](https://www.pivotaltracker.com/story/show/165477075).
