### ISSUE TITLE
Enable Performance Insights on RDS Instances

### ISSUE THREAD

**Issue by sheyd** [DoSomething/infrastructure#113]
7 days for RDS instances is free and will allow us to have Monyog like monitoring for our databases.

**Comment by sheyd** [comment]
Unfortunately, this is currently only supported for RDS Aurora clusters. [This](https://github.com/terraform-providers/terraform-provider-aws/issues/5259) Terraform issue, and [PR](https://github.com/terraform-providers/terraform-provider-aws/pull/6453) will hopefully enable this functionality. For now, I might manually set these up for Quasar to test out.

**Comment by sheyd** [comment]
I'd already set this up when creating the Quasar RDS instances. 😂

**Comment by DFurnes** [comment]
Tracking this in [#165497741](https://www.pivotaltracker.com/story/show/165497741).
