### ISSUE TITLE
Set `monitoring_interval` on RDS Instances to 10 seconds

### ISSUE THREAD

**Issue by sheyd** [DoSomething/infrastructure#115]
AWS best practice recommended via https://www.youtube.com/watch?v=6YmcteXoBvU.

**Comment by sheyd** [comment]
I manually set this interval on Quasar DB instances, and @DFurnes was gracious enough to include it in https://github.com/DoSomething/infrastructure/commit/cc4004b59a8d8c3f2de00b00a5504e8b24a5f8e0 to not mess up Terraform state.

**Comment by DFurnes** [comment]
Closing in favor of [#165497627](https://www.pivotaltracker.com/story/show/165497627).
