### ISSUE TITLE
Standardize how we use continuous integration in projects.

### ISSUE THREAD

**Issue by DFurnes** [DoSomething/infrastructure#139]
We currently use [Wercker][1] and three(!!) separate [Jenkins][2] instances to run tests on pull requests, automatic & manual deploys, and scheduled jobs (like database refreshes). It would be nice to standardize how we handle this across the board.

### Requirements
There are a few requirements I think our CI system must satisfy:
- We **must be able to author jobs and workflows in code**. This is important for visibility, tracking changes over time, and ensuring that changes go through a standard review process.
- We need support for jobs that trigger on pull requests, commits to `master`, and scheduled tasks.
- We don't want to manage "raw" infrastructure ourselves (e.g. being responsible for securing or updating software on our own Jenkins instance).

Ideally, we'd also satisfy these requirements:
- The CI tool should run jobs in Docker containers so we don't have to worry about environment inconsistencies, like updating a dependency used by one project breaking another.
- We should not be the only organization using the service. (Seriously, who else uses Wercker?)
- Ideally, we could use a free/open-source (or low-cost) plan.

### Options

We currently use [Wercker][1] and [Jenkins][2]. I think we can rule out Jenkins, since there doesn't seem to be a good "hosted" option (and maintenance for these instances is a continuous drain on our engineering bandwidth). Wercker has met our needs in the past, but it seems to have stagnated under the Oracle umbrella & I've never run into anyone else who uses it.

Some other options that are worth investigating are [CircleCI][3], [Drone.io][5], and [Travis CI][4].

[1]: https://www.oracle.com/corporate/acquisitions/wercker/
[2]: https://jenkins.io
[3]: https://circleci.com
[4]: https://travis-ci.org
[5]: https://drone.io

**Comment by mshmsh5000** [comment]
Seriously, [who uses Wercker?](https://stackshare.io/wercker/in-stacks) I don't recognize any of those companies.

**Comment by mshmsh5000** [comment]
One note from a nonprofit CTO re: CircleCI vs Drone:

>We are in the process of moving from CircleCI to Drone right now, primarily due to costs. No strong opinions, because CircleCI has worked well and our experience in Drone.io is relatively new. Our costs on Circle went up by about 8x or so with their new pricing model for larger containers and based on our volume. We previously had a great discount.

Good flag to watch costs carefully as we try adding workloads to Circle. Jenkins, for all its shortcomings, is free, and we've never had to think twice about setting up a job on there.

**Comment by mshmsh5000** [comment]
For that team ^^^, Drone costs "$0 for us as a non-profit and open source codebase."

From another org, a moderate endorsement of Travis:

>We were also part of the group that had to find a replacement for Wercker and we went the Travis route. So far nothing to complain about.

**Comment by weerd** [comment]
Going to close this issue since we no longer use Wercker and have shifted our now consolidated repositories to use CircleCI (although we still use Jenkins a bit for database refreshes!).
