### ISSUE TITLE
Create unique S3 bucket name for Lookerbot.

### ISSUE THREAD

**Issue by mshmsh5000** [DoSomething/infrastructure#142]
Sooo, it turns out that someone already thought to name their S3 bucket "lookerbot", and S3 names need to be [unique across all of S3](https://docs.aws.amazon.com/AmazonS3/latest/gsg/CreatingABucket.html). Because of this, the S3 changes in the original PR (#136) failed to deploy.

Let's try `ds_lookerbot_images`, just to make sure.

**Comment by DFurnes** [comment]
For consistency with our other S3 buckets, can we name this `dosomething-lookerbot` or `dosomething-lookerbot-images` instead?

**Comment by mshmsh5000** [comment]
Love it

**Comment by mshmsh5000** [comment]
Closed by #144.
