### ISSUE TITLE
Allow some crawlers on servers outside US access to our environments.

### ISSUE THREAD

**Issue by weerd** [DoSomething/infrastructure#17]
![facebook crawler coming from outside us](https://user-images.githubusercontent.com/105849/47225983-54b81600-d38d-11e8-9ed3-622a8d777611.png)

When trying to debug and test meta tags in our HTML pages, ran into an issue where a `www-dev.dosomething.org` URL was returning the "Sorry" page for all users outside of the US due to our current approach to deal with GDPR.

This poses a problem when testing if crawlers that exist outside the US can't read our pages properly and are getting redirected.

**Comment by DFurnes** [comment]
Gah, GDPR strikes again! It looks like this has definitely happened for other links:

![screen shot 2018-10-19 at 11 38 31 am](https://user-images.githubusercontent.com/583202/47228606-a368ae80-d393-11e8-9f0d-9c71571124cc.png)

**Comment by weerd** [comment]
Better to find out late than never! 😬
