### ISSUE TITLE
Convert HAProxy instance to a Fastly property w/ Fastly Anycast.

### ISSUE THREAD

**Issue by blisteringherb** [DoSomething/infrastructure#29]
_ISSUE_
-------------------
#### Current Behavior
- The Footlocker cert expired, and I've renewed it using Let's Encrypt. We'd like to continue using Let's Encrypt going forward for all our properties because it's free and because it will auto-renew. The certs have to be renewed every 90 days which would be a non-issue if we were pointing directly to the webserver by using a cron job, but because we're using HAProxy we have to go through some somewhat extraordinary measures to utilize the Let's Encrypt auto-renew features. 

#### Desired Behavior
- Per @sheyd's suggestion, we should migrate the old HAProxy box to Nginx so we can take advantage of the auto-renew features so we eliminate these issues for good in the future. This will also have the added benefit of cleaning up that config and removing cruft that's no longer necessary.

#### Why This Matters
- We don't want to have to think about certs anymore!

#### Properties Affected (optional)
- Including but not limited to Footlocker, HRBlock, and other properties that go through the current standalone HAProxy box

NOTE: Footlocker will expire 1/29/19 and HRBlock will expire 12/9/18

**Comment by sheyd** [comment]
This *might* be possible to do via Fastly Anycast IP [service](https://docs.fastly.com/guides/basic-configuration/using-fastly-with-apex-domains). I'm opening up a support ticket per talking to Matt since we technically have a paid account and this is a free service.

Also talked to @blisteringherb to pause on this ticket so we're not burning cycles.

**Comment by DFurnes** [comment]
Yeah, if we can handle this with a Fastly service that'd be the dream (both for parity with how we handle other parts of our infrastructure, and because we've wanted other Fastly features like GeoIP headers for these apps in the past).

Another compelling idea we talked about would be to handle this with an Elastic IP + ELB + ECS Nginx container, so that we can provision and store this configuration in code.

**Comment by sheyd** [comment]
Ticket opened!

**Comment by sheyd** [comment]
So a little bit of a good news/annoying news situation here:

<b>Good News™</b>
We can absolutely use Fastly Anycast to have as IP's we set for apex and secondary domains. The steps involve:
- Adding the domains under TLS management [here](https://manage.fastly.com/account/tls/domains).
- Go through certificate domain validation process (usually adding a TXT record for the domain).
- Under `DNS Details` next to the domain, there are A records that are the Anycast IP's. 
- Send those IP addresses to clients to put in their DNS records for apex and secondary domains.

<b>Annoying News</b>
One of the annoying issues would be that for certificate validation for Footlocker and HR Block properties, we have to get in touch with their DNS providers for TXT records, and that process has historically been a bit onerous. Might be worth chatting with Caroline and Daniel about this to determine LOE. But, I think for a solution for us to maintain this logic in Fastly and deprecating the HA Proxy/Nginx server(s) we maintain, we're 💯 good to go here.

**Comment by DFurnes** [comment]
Woohoo! That's extremely exciting. 🎉 We can probably just hold on this until each scholarship re-opens since that'd be a good way to get these moved along on the partner's end.

**Comment by sheyd** [comment]
Good call. The HR Block cert expires on 12/9/2018, so for the short-term, if we can re-up the Comodo one for 1 year, I think it's a cheap extension till we can migrate them in February.

**Comment by DFurnes** [comment]
Closing this in favor of [#165497441](https://www.pivotaltracker.com/story/show/165497441).
