### ISSUE TITLE
QUESTION: Fastly pass-through property for vote.ds?

### ISSUE THREAD

**Issue by mshmsh5000** [DoSomething/infrastructure#3]
Coming out of the National Voter Reg Day pre-mortem, we've asked ourselves whether the easiest way to redirect `vote.ds` as a contingency is to position a Fastly layer now, set with a minimal pass-through configuration. If we do need to do any redirects, and with those any URL/param transformations, we could do them via Fastly.

**Comment by DFurnes** [comment]
Yeah, I'm very into this. Should we spin up a prototype?

**Comment by mshmsh5000** [comment]
Yes please! Only question for me is about level of effort and your bandwidth between now and NVRD. That's your call to make.

**Comment by DFurnes** [comment]
I'm tackling this in #3! So far I've got a simple pass-through property pointing to our Instapage backend running at [https://vote-fastly.dosomething.org](vote-fastly.dosomething.org) which seems to be functioning as expected.

**Comment by DFurnes** [comment]
Going to close this issue out! We enabled a pass-through Fastly property in #4, and have backup plans ready in case Instapage goes down in #5 (redirects) and #6 (static snapshots). ⚒
