### ISSUE TITLE
Improve Northstar performance & concurrency.

### ISSUE THREAD

**Issue by DFurnes** [DoSomething/infrastructure#31]
This is a follow-up ticket from DoSomething/devops#383.

#### Background
We successfully moved Northstar from AWS (an m4.xlarge EC2 instance) to Heroku (1-5 autoscaled Performance-M dynos). This simplified our operations & also allows us to scale up-and-down based on demand more easily. I've monitored performance and made some adjustments since then:

From [July 17th 2018's broadcast](https://github.com/DoSomething/devops/issues/383#issuecomment-406007425):

> We ran a couple of broadcasts yesterday - a smaller 11:00am broadcast, and a 2:00-8:30pm full-list broadcast (which is continuing today). Both were [set to run at 75rps](https://dosomething.slack.com/archives/C02BBRN5A/p1531504265000143), and seem to have happily [ran at between 70-85rps(!!)](https://dosomething.slack.com/archives/C02BBRN5A/p1531921749000455). Here's what [New Relic](https://rpm.newrelic.com/accounts/108038/applications/92216128) had to say:
> 
> ![screen shot 2018-07-18 at 11 12 06 am](https://user-images.githubusercontent.com/583202/42890869-ec39aae4-8a7b-11e8-9d53-d6f91bcb8188.png)
> 
> And here's that same response time graph overlaid over auto-scaling events:
> 
> ![screen shot 2018-07-18 at 1 09 53 pm](https://user-images.githubusercontent.com/583202/42896738-e17895b0-8a8b-11e8-94a0-ac52f3f31526.png)
> 
> It's interesting to see how much scaling fluctuates between 2-4 dynos when under load, which perhaps suggests we should drop our desired p95 response time a little more (currently at 750ms, curious to try 500ms again).

And [the following day](https://github.com/DoSomething/devops/issues/383#issuecomment-406034442) when we finished that broadcast:

> I think one problem we're running into with auto-scaling is that it's entirely based on response time, so if we get good performance at 3 dynos, we scale down to 2 until things bog down, and then back up... for example, here's the hour from 12:50-1:50pm with a target 500ms p95 response time:
> 
> <img width="485" alt="screen shot 2018-07-18 at 4 59 25 pm" src="https://user-images.githubusercontent.com/583202/42907494-f5837ea6-8aab-11e8-86d0-c63b05ab993d.png">

#### Current Behavior
I think we've found the sweet spot for p95 response time (750ms). This seems to let us spin up quickly enough when throughput spikes, but still happily provisions down to 1 dyno when throughput drops.

I think the remaining scaling issues we're seeing come from alternatingly over- and under-provisioning,  since Heroku's autoscaling is [based on the past hour's performance](https://blog.heroku.com/heroku-autoscaling#how-it-works) (so we scale up when things get too slow, but then as soon as they're under control we scale back down again... gah!!)

While things seem to be working mostly okay, we do still see some slow requests & 503s when in one of those underprovisioned "dips" (until we scale back up again).

#### Desired Behavior
We may want to consider handling scaling ourselves (based on throughput), or further [tuning performance](https://github.com/DoSomething/devops/issues/383#issuecomment-406315352) to get more out of each individual dyno.

#### Why This Matters
We want to make sure we're getting the best performance bang for our buck! Specifically, we want to make sure that we can get the most throughput when we need to make a ton of API requests to Northstar during a broadcast.

**Comment by DFurnes** [comment]
Alright, I've enabled shielding for our backend services in #32 and confirmed that caching seems to be working much more reliably now. I'm going to whip up a little script to warm up the cache for those users we sent a broadcast to yesterday so we're back to where we should be! 👌

**Comment by DFurnes** [comment]
I tested this out by warming up a ton (~500k) user profiles in Fastly the other day. We no longer have any issues with cache misses due to connecting to different POPs, but we were foiled by Fastly's default TTL of an hour! I've set this to a year for these responses in DoSomething/northstar#811 and we'll see how much we get out of that!

**Comment by DFurnes** [comment]
Unfortunately, caching in Fastly doesn't look like it'll be the panacea we'd hoped it might be. While all the profiles seemed to stay cached through the end of the day on Friday with the increased TTL, most had been evicted when I checked again this morning.

I think our best remaining option here is to reduce the number of requests that Gambit needs to make in order to send off a broadcast, either through Twilio's [bulk-send functionality](https://www.twilio.com/blog/2017/12/send-bulk-sms-twilio-node-js.html), or by having Northstar notify Gambit/Blink to remove any queued outgoing messages to a user when they're unsubscribed.

**Comment by rapala61** [comment]
Thanks so much for all your hard work in caching NS requests in Fastly! Maybe a jam w/ @aaronschachter would be a good idea to discuss next steps/ideas! cc @ngjo

**Comment by ngjo** [comment]
Yea, I think it'd make sense for @aaronschachter to dig into Twilio bulk some more (that's on this sprint's docket) and regroup then on that front. I've also created an [opportunity assessment](https://docs.google.com/a/dosomething.org/document/d/16Py_lH_28lsv3vgdxPMVDvTJZp__JiC0WeNKbxMT1dE/edit?disco=AAAACV7Pdac&ts=5be0a13f&usp=comment_email_document) for integrating w/ Twilio bulk should Aaron's findings suggest that's a good path to continue on, we could tackle that in Q1. In this doc too, it includes more details about what @DFurnes mentioned re:Northstar notifying Gambit/Blink to remove queued outgoing messages -- we should also put in a prod opportunity assessment for this work in case we do want to pursue this in Q1 (I can do this and share around).

So I'm thinking once we have the Twilio bulk write-up we can regroup towards the end of Nov/early Dec to talk next steps. In the meantime though, @DFurnes would you be available to scale Northstar up for sends until we get to a more automated solution?

**Comment by DFurnes** [comment]
I'm going to close this out, since I believe we've exhausted the possibilities for handling this on Northstar's end and have two opportunity assessments lined up to re-think this on Gambit's end: [SMS Send Speed / Changing Order of Operations for Sends](https://docs.google.com/document/d/1USf7ZSVxBFttPcnfL-qk3WFwkzqHkC4lgRl5FOvZaq8/edit) & [SMS Send Speed (Twilio Bulk)](https://docs.google.com/document/d/16Py_lH_28lsv3vgdxPMVDvTJZp__JiC0WeNKbxMT1dE/edit).
