### ISSUE TITLE
Migrate Infrastructure Jenkins Jobs to Code/Heroku

### ISSUE THREAD

**Issue by sheyd** [DoSomething/infrastructure#40]
_BUG_
-------------------
#### Current Behavior
- A miscellaneous number of tasks remain in the Production Jenkins environment that handles tasks like weekly DB refreshes from Prod to QA.

#### Desired Behavior
- Most of these tasks are just wrapper scripts around bash jobs or other similar utilities. They can and should be moved to code in a repo and run via the Heroku scheduler in one place.

#### Why This Matters
- We're not capturing this critical part of infrastructure in code. It provides simple but vital services, and should be run with production grade attention to detail, documentation, and tracking.

**Comment by DFurnes** [comment]
Going to fold this into the write-up in #139.
