### ISSUE TITLE
Move all Longshot environments for Foot Locker & HR Block to RDS

### ISSUE THREAD

**Issue by ngjo** [DoSomething/infrastructure#41]
_FEATURE OVERVIEW_ 
------------------------------------------ 
### User Story
As DS, we want every Longshot environment for Foot Locker internal, external and HR Block to be on RDS so that it handles automated backups, upgrades, and availability.

### Additional Information 
[This was done for Foot Locker production here](https://github.com/DoSomething/devops/issues/434)

[Related ticket](https://github.com/DoSomething/devops/issues/168)

This was also resurfaced in a Longshot post-mortem as a next step [here](https://docs.google.com/document/d/1Jh4x99KRA-5Ghhoha_kCV_B9r1dBjav5gS0MIU0ieao/edit?ts=5bad18c9#)

Tentative soft launch date for HR Block is Nov 6, hard launch is Nov 7

### Why This Matters 
We want more stability with the Longshot app across environments

### Definition of Done 
Given that I'm a DS dev
When I look at any Longshot environment
Then it's on RDS and things are working as expected

### Additional Things to Consider for Done
(1) Test needed? 
(2) Documentation needed?

**Comment by DFurnes** [comment]
I've moved Footlocker Internal into RDS in #49, closing this out. @katiecrane Once we swap over to the new database instance for H&R Block, I'll hook you up with database credentials there!
