### ISSUE TITLE
Make it clearer what environment an app is in.

### ISSUE THREAD

**Issue by DFurnes** [DoSomething/infrastructure#47]
It can sometimes be confusing to see what environment you're in. Even with our [simplified naming scheme](https://github.com/DoSomething/devops/issues/366), you still have to look at the URL to see where you're at, e.g. `activity-qa` vs. `activity`. This makes it easier than it should be to make a change in the wrong place, or wonder why your local changes aren't applying because you're refreshing QA! Oof!

I introduced the idea of "environment badges" in GraphQL last year, but never had a chance to roll them out further. I'd like to build a small library to make it easy to add the same feature everywhere:

![screen shot 2018-11-08 at 10 56 03 am](https://user-images.githubusercontent.com/583202/48210528-7d587d80-e345-11e8-8fbe-9f8f8a1131d6.png)

**Comment by mshmsh5000** [comment]
Love it—I always appreciate this [in Drupal](https://www.drupal.org/project/environment_indicator).
