### ISSUE TITLE
Capture Quasar Config in Terraform

### ISSUE THREAD

**Issue by sheyd** [DoSomething/infrastructure#48]
- [x] Quasar QA DB, Security Groups, and Options Group
- [x] Quasar Prod DB, Security Groups, and Options Group

**Comment by sheyd** [comment]
Adding to this parameter group settings, since we've migrated to RDS via https://www.pivotaltracker.com/story/show/161654902, and one thing we lost was the Heroku auto-tuning they do on their end. 

We have to do some performance tweaks to RDS instance via https://www.pivotaltracker.com/story/show/162208643.

**Comment by DFurnes** [comment]
@sheyd Is this good to close out? 🎉

**Comment by sheyd** [comment]
🎆 🍾
