### ISSUE TITLE
Set up a DNS record for `www.caps.hrblock.com` and redirect 

### ISSUE THREAD

**Issue by ngjo** [DoSomething/infrastructure#80]
When we were testing the Heroku switch we noticed that http://www.caps.hrblock.com/ doesn't redirect to the correct page, https://caps.hrblock.com/. We'd like to set up a DNS record for that URL and redirect it so that users are getting to the site!

From [this](https://dosomething.slack.com/archives/C03T8SDMW/p1543347372041500?thread_ts=1543344112.038100&cid=C03T8SDMW) Slack conversation.

**Comment by DFurnes** [comment]
Since we don't own `hrblock.com`, this is something we'll need to reach out to our partners there to get set up. Do we have an existing contact from when we originally set up this DNS record?

**Comment by DFurnes** [comment]
This is also something that's probably worth bundling with DNS changes for #29.

**Comment by sheyd** [comment]
Also note, we'd have to get another certificate for `www.caps.hrblock.com`, since wildcard domains only work for tertiary domain levels.

**Comment by ngjo** [comment]
Synced w/ Caroline and she's going to bring this up on the client check-in next Wednesday, 12/19

**Comment by DFurnes** [comment]
Tracking this in [#165498288](https://www.pivotaltracker.com/story/show/165498288).
