### ISSUE TITLE
Figure Out Where to Put Infrastructure Documentation

### ISSUE THREAD

**Issue by sheyd** [DoSomething/infrastructure#97]
I'd love everyone tagged on this ticket thoughts on where to house cross-eng infrastructure documentation. Dave and I have discussed this a little bit, but I think it warrants a standardized approach in 2019. Examples of documentation would be:
1. How do you connect to MongoDB databases from your dev machine?
2. How do you connect to MariaDB databases from your dev machine?
3. What's the normal caching rules for our Fastly properties?

While something like point 3 can probably exist in the infrastructure repo, I think it'd be great to have at-a-glance infrastructure info that anyone can look at for our most pertinent information. Do we want to use GitBooks in this repo? Readme in a dedicated infra-doc repo? Something else entirely?

**Comment by DFurnes** [comment]
Tracking this work in [#165498501](https://www.pivotaltracker.com/story/show/165498501).
