### ISSUE TITLE
Retire celebsgonegood.com infrastructure

### ISSUE THREAD

**Issue by mshmsh5000** [DoSomething/infrastructure#98]
This is now being served by Instapage, so we can truly retire everything related to CGG, including the Fastly property.

**Comment by DFurnes** [comment]
We're still serving a static snapshot of http://www.athletesgonegood.com off of this Fastly property & S3 bucket, but definitely worth cleaning up the CGG part! 💯

**Comment by mshmsh5000** [comment]
So I imagine for an issue like this, we'd first delete the references from the [Terraform config](https://github.com/DoSomething/infrastructure/blob/master/voting-app/main.tf#L5), and then optionally create a follow-up issue to delete the underlying resource. Is that right?

In this case, we might want to keep the underlying S3 bucket for posterity, so just want to clarify the process.

**Comment by DFurnes** [comment]
Yep, we'd delete the references from the Terraform config and those underlying resources would be removed when we ran `terraform apply`. For things we want to keep, we should keep the Terraform resource.

**Comment by mshmsh5000** [comment]
Ah, so maybe we should just leave these be? Or delete the Fastly references but keep the S3 reference?

**Comment by DFurnes** [comment]
I think it depends how likely we are to want to reuse that bucket. Since it's such an old snapshot of the site (from 2016), I'd imagine its unlikely we'll want it back. And worst case, I had also placed those snapshots in [this repository](https://github.com/DoSomething/voting-app-static) if we need to re-create.

**Comment by DFurnes** [comment]
This was done in #117! 🎬
